dist: trusty
language: ocaml
cache:
  apt: true
  directories:
  - $HOME/.opam
  - $HOME/Library/Caches/Homebrew
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=2
  - OPAMYES=true
  - OPAMKEEPBUILDDIR=true
  matrix:
      - COMPILER="4.04.0+afl"
      - COMPILER="4.05.0+afl"
      - COMPILER="4.06.1+afl"
      - COMPILER="4.07.0+afl"
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
os:
    - linux
    - osx
branches:
  except:
  - /FuzzChick.*/

before_install:
    if [ $TRAVIS_OS_NAME = osx ]; then
    brew update; brew install opam; fi

install:
- travis_wait opam init -j ${NJOBS} --compiler=${COMPILER} -n
- eval $(opam config env)
- opam config var root
- opam repo add coq-released https://coq.inria.fr/opam/released || true
- travis_wait opam upgrade
- opam list
- ocamlc -v

script:
- set -e
- echo 'Building QuickChick...';
  echo -en 'travis_fold:start:QuickChick.build';
  opam update;
  travis_wait 40 opam pin add . ;
  travis_wait opam install coq-quickchick;
  echo -en 'travis_fold:end:QuickChick.build'
- echo 'Testing IFC...';
  echo -en 'travis_fold:start:QuickChick.test.ifc-basic';
  make -C examples/ifc-basic;
  echo -en 'travis_fold:end:QuickChick.test.ifc-basic'
- echo 'Testing Red-black tree...';
  echo -en 'travis_fold:start:QuickChick.test.RedBlack';
  make -C examples/RedBlack;
  echo -en 'travis_fold:end:QuickChick.test.RedBlack'
- echo 'Testing STLC...';
  echo -en 'travis_fold:start:QuickChick.test.stlc';
  make -C examples/stlc;
  echo -en 'travis_fold:end:QuickChick.test.stlc'
- echo 'Testing Multifile Mutation...';
  echo -en 'travis_fold:start:QuickChick.test.multifile-mutation';
  make -C examples/multifile-mutation test;
  echo -en 'travis_fold:end:QuickChick.test.multifile-mutation'
- echo 'Testing C Mutation...';
  echo -en 'travis_fold:start:QuickChick.test.c-mutation';
  make -C examples/c-mutation test;
  echo -en 'travis_fold:end:QuickChick.test.c-mutation'
- echo 'Testing -N option...';
  echo -en 'travis_fold:start:QuickChick.test.less';
  make -C examples/c-mutation lesstest;
  echo -en 'travis_fold:end:QuickChick.test.less'
- echo 'Testing Python I/O...';
  echo -en 'travis_fold:start:QuickChick.test.python-io';
  make -C examples/python-io lesstest;
  echo -en 'travis_fold:end:QuickChick.test.python-io'
- echo 'Removing QuickChick...';
  echo -en 'travis_fold:start:QuickChick.remove';
  opam remove --force coq-quickchick;
  echo -en 'travis_fold:end:QuickChick.remove'
