name: Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:8.15'
          - 'coqorg/coq:8.16'
          - 'coqorg/coq:8.17'
          - 'coqorg/coq:8.18'
          - 'coqorg/coq:8.19'
          - 'coqorg/coq:8.20'
          - 'rocq/rocq-prover:9.0'
          - 'rocq/rocq-prover:dev'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-quickchick.opam'
          custom_image: ${{ matrix.image }}
          before_install: |
            startGroup "Setup and print opam config"
              opam repo -a --set-default add coq-extra-dev https://coq.inria.fr/opam/extra-dev
              opam config list; opam repo list; opam list
            endGroup
          after_script: |
            startGroup "Test dependants"
              PINS=$(opam list -s --pinned --columns=package | xargs | tr ' ' ,)
              PACKAGES="coq-http"
              for PACKAGE in $PACKAGES
              do DEPS_FAILED=false
                 opam install -y --deps-only $PACKAGE || DEPS_FAILED=true
                 [ $DEPS_FAILED == true ] || opam install -t $PACKAGE
              done
            endGroup
            set -o pipefail  # recommended if the script uses pipes

            startGroup "Generate Coqdoc"
              make -j`nproc` coqdoc || echo "Failed to generate Coqdoc"
            endGroup
          before_script: |
            startGroup "Workaround permission issue"
              sudo chown -R 1000:1000 .
            endGroup
          export: 'OPAMWITHTEST OPAMCONFIRMLEVEL'
        env:
          OPAMWITHTEST: true
          OPAMCONFIRMLEVEL: unsafe-yes
      - name: Revert permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .
      - uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: coqdoc
          path: html
          overwrite: true

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
